packages:
  - "."

onlyBuiltDependencies:
  - "@prisma/engines"
  - prisma

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
